# Generated by Django 4.0.1 on 2022-01-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Öğrenci Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Öğrenci Soyad')),
                ('section', models.TextField(verbose_name='Bölüm')),
                ('number', models.CharField(max_length=50, verbose_name='TC Kimlik No')),
                ('midterm_exam', models.CharField(max_length=50, null=True, verbose_name='Vize Notu')),
                ('final_exam', models.CharField(max_length=50, null=True, verbose_name='Final Notu')),
                ('exam_average', models.CharField(max_length=50, null=True, verbose_name='Harf Notu')),
            ],
        ),
    ]
