# Generated by Django 4.0.1 on 2022-01-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='harf',
            field=models.CharField(max_length=50, null=True, verbose_name='Harf Notu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_average',
            field=models.FloatField(null=True, verbose_name='Harf Notu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='final_exam',
            field=models.FloatField(null=True, verbose_name='Final Notu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='midterm_exam',
            field=models.FloatField(null=True, verbose_name='Vize Notu'),
        ),
    ]
