# Generated by Django 4.0.1 on 2022-01-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0003_rename_harf_student_letter_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_average',
            field=models.FloatField(null=True, verbose_name='Ortalama Not'),
        ),
    ]
